name: Automatización Resiliente con Latencia Aleatoria (Sin Docker)

on:
    push:
        branches: [ main ]

jobs:
    run-automation-suite:
        name: Ejecucio de Pruebas y Reporte
        runs-on: ubuntu-latest

        steps:
            - name: 1. Descargar el codigo del Repositorio
              uses: actions/checkout@v4

            - name: 2. Configurar Entorno Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
            
            - name: 3. Configuracion local con Docker
              run: |
                cd src
                docker compose up --build -d

            - name: 4.Instalar Dependencias de Pruebas (Playwright)
              run: |
                npm ci
                npm install --save-dev wait-on @playwright/test
                node ./node_modules/playwright/cli.js install --with-deps

            - name: 5. Ejecutar Script de prueba en modo Headless
              run: |
                cd tests
                node ./node_modules/playwright/cli.js test ./registro-async.spec.js --repeat-each=3

            - name: 6. Subir reporte Playwright
              if: always()
              uses: actions/upload-artifac@v4
              with:
                name: playwright-report
                path: tests/playwright-report/



